### ISSUE TITLE
wine/mono?

### ISSUE THREAD

**Issue by nonchip** [tmedwards/CoCEd#10]
> Not currently compatible with Mac OS X and Linux (even if using Wine or Mono).

why would you do this? can't be *that* hard to make it compatible, unless you are for some reason (ab-)using another "cutting edge microsoft technology" (aka. unstable bloatware)…

**Comment by tmedwards** [comment]
CoCEd uses WPF for it's user interface.  As to why it does, I'm assuming the original author (Perdev) was very familiar with WPF and cross-platform compatibility wasn't really a priority for him.

The Mono developers decided that they didn't want to write a WPF compatible library.  If you have a beef with that, take it up with them.  Tangentially, now that MS is open sourcing parts of .NET themselves, a port of WPF might actually get done.

The caution against Wine may no longer be applicable—I haven't tested in a very long while, nor has anyone done so and let me know about it.  It's possible that, at this point, if one installed all of the requisite .NET packages into a Wine container, it might actually be possible to get CoCEd running within it.

**Comment by nonchip** [comment]
> The caution against Wine may no longer be applicable—I haven't tested in a very long while, nor has anyone done so and let me know about it. 

i just tried:

    fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
    fixme:ole:RemUnknown_QueryInterface No interface for iid {00000019-0000-0000-c000-000000000046}
    The entry point method could not be loaded

maybe i'm missing some .net libs i'm unaware of, but there's not even a "you need .net" popup you usually get from the PE section of the exe. just those 3 lines on stdout.

**Comment by nonchip** [comment]
if you have any ideas what might be missing, i'd be willing to do more testing.

**Comment by tmedwards** [comment]
I don't know what you've installed in your Wine container/bottle, nor what version of Wine you're using, so I couldn't say what you're missing.  I probably couldn't help you if I did—as I said before, it's been a while since I've had a reason to touch Wine.  You'd probably have better luck checking at the Wine project's website—I know they, generally, keep track of what things (e.g. .NET frameworks) install, and work, on which versions of Wine and how to get them installed.

Here is the .NET 4 (full version) entry in WineHQ's app database.

* [WineHQ > AppDB > .NET Framework 4.0](https://appdb.winehq.org/objectManager.php?sClass=version&iId=17886 "https://appdb.winehq.org/objectManager.php?sClass=version&iId=17886")

That said, I can tell you that CoCEd is written in C#, uses WPF, and targets the .NET Framework 4 Client Profile.  In theory, you may only need one of these .NET 4 installers (and anything it might require):

* [Microsoft .NET Framework 4 Client Profile (Standalone Installer)](https://www.microsoft.com/en-us/download/details.aspx?id=24872 "https://www.microsoft.com/en-us/download/details.aspx?id=24872") — Only the .NET 4 Client Profile.
* [Microsoft .NET Framework 4 (Standalone Installer)](https://www.microsoft.com/en-us/download/details.aspx?id=17718 "https://www.microsoft.com/en-us/download/details.aspx?id=17718") — The full .NET 4.
