### ISSUE TITLE
I have no idea how this works

### ISSUE THREAD

**Issue by Nick501** [tmedwards/CoCEd#12]
So I have tried to save to file from CoC and then find it with the Open option in the editor. This doesn't work because for some odd reason the saves don't show up in the folders where I put them. I don't know entirely what I'm doing wrong. I have the CoC swf saved and I open it in my browser, save to file and go to the place I saved it to find that it isn't there.

**Comment by tmedwards** [comment]
Choosing the correct save format in the import dialog would probably help.

The two ways to save CoC files (slot saves and saves to file) are not compatible.  Using the slot save menus this is handled automatically, since they should all be slots saves.  When you choose to import or export a save, however, CoCEd can't know which format you want to import/export, so there's a setting in the dialogs to control this.  The setting defaults to the slot save format, so changing it to the save to file format should allow you to see the file.
