### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by Megabozoman** [tmedwards/CoCEd#14]
ok so I don't know if i'm stupid and missed a step or something but i can't open the .exe no matter what i try I don't get any error messages or anything it just wont open I am using a vista laptop and have the .net files and i extracted the files from the archive but it won't work plz help

**Comment by tmedwards** [comment]
If you have the proper version of .NET installed and you properly extracted the archive and you're not receiving errors of any kind, then the only thing that springs to mind is an over aggressive anti-virus/malware suite.

You might try checking the logs of whatever AV/M software you're using to ensure that it's not blocking CoCEd.

**Comment by Megabozoman** [comment]
well i checked my av/m software and  as far as i can tell they don't seem to be the problem

**Comment by tmedwards** [comment]
Windows Vista did not ship with .NET 4, which is a requirement of CoCEd.  Have you installed it?

You need to have one of either the [Microsoft .NET Framework 4 Client Profile](https://www.microsoft.com/en-us/download/details.aspx?id=17113 "https://www.microsoft.com/en-us/download/details.aspx?id=17113") or the [Microsoft .NET Framework 4](https://www.microsoft.com/en-us/download/details.aspx?id=17851 "https://www.microsoft.com/en-us/download/details.aspx?id=17851") installed.  The client profile is a lighter install and is what CoCEd targets, though the full framework install will also work.

Other than that, I don't know.  Since you're not getting an error, I can't even begin to speculate.
