### ISSUE TITLE
Trojan Virus?

### ISSUE THREAD

**Issue by ZemogB** [tmedwards/CoCEd#15]
Ive been using this for awhile, and have had no problems. 
But for whatever reason, my computer is saying that this contains a trojan virus. its never said that before, ive used this once or twice in the past and this is just strange to me that its randomly saying that it has a trojan virus.

**Comment by tmedwards** [comment]
If you knew how many false positives legitimate software developers have to put up with, you wouldn't be surprised.

The code contains no viruses or malware.  The releases are hosted here on GitHub, so the chance of someone being able to taint a release is small.

What version?  I just download and scanned the latest release `v1.3.1` from here at https://www.virustotal.com and received no positives at all.  My local anti-virus/-malware also didn't so much as twitch.

**Comment by ZemogB** [comment]
It was v1.3.1, My local antivirus sofware wont even allow me to download it.

**Comment by tmedwards** [comment]
I don't know what to tell you.  I think we've established that CoCEd is not the problem here.  Obviously, something on your system has changed, since you stated that you were able to use it before without issues.  Unfortunately, I have no idea what might have changed.

The best I can offer is to suggest that you ensure your AV/M definitions are up to date—you didn't note which version of Windows you're using, however, if its Win XP, then MSE no longer supports your OS—and, perhaps, that your .NET 4 install is not damaged/corrupted.

**Comment by tmedwards** [comment]
Might as well post this here too.

Seeing that it's probably a MSE definition issue, I've submitted a complaint with Microsoft contesting MSE's classification of CoCEd.  We'll see where that goes.

**Comment by JynxZox** [comment]
I am using Windows 7 and keep my definitions up to date, i have no clue all i can tell you what happen 30 mins ago when i downloaded coced 1.3.1 was attached by Microsoft Security Essentials and this does not happen with CoCed 1.3.0
